# osx_image: xcode11.2 settings
# https://docs.travis-ci.com/user/reference/osx#Xcode-version
language: swift # or objective-c

osx_image: xcode10.2
git:
  depth: 1
  submodules: false
branches:
  only:
    - master

# cache
# https://stackoverflow.com/questions/39930171/cache-brew-builds-with-travis-ci
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
before_cache:
  - brew cleanup

before_install:
  # - export PATH=/usr/local/opt/llvm/bin:"${PATH}"
  - export PATH="/usr/local/opt/llvm@8/bin:$PATH"
  - brew update
  - brew install llvm@8
  - git clone https://github.com/llvm-swift/LLVMSwift
  - sudo swift LLVMSwift/utils/make-pkgconfig.swift
  - swift run -Xlinker -w
  - swift test -Xlinker -w
