# osx_image: xcode11.2 settings
# https://docs.travis-ci.com/user/reference/osx#Xcode-version
language: swift # or objective-c
# xcode_project: JSONDecodeKit.xcodeproj # path to your xcodeproj folder
# xcode_scheme: JSONDecodeKit
# podfile: pod # Disable `pod install`
osx_image: xcode10.2
git:
  depth: 1
  submodules: false
branches:
  only:
    - master

# cache
# https://stackoverflow.com/questions/39930171/cache-brew-builds-with-travis-ci
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
before_cache:
  - brew cleanup

before_install:
  - export PATH=/usr/local/opt/llvm/bin:"${PATH}"
  - brew update
  - brew install llvm
  - git clone https://github.com/llvm-swift/LLVMSwift
  - sudo swift LLVMSwift/utils/make-pkgconfig.swift
  - swift test

# script:
#   - set -o pipefail
#   - brew install llvm@8
#   - export PATH=$PATH
#   - git clone https://github.com/llvm-swift/LLVMSwift
#   - swift LLVMSwift/utils/make-pkgconfig.swift
#   - swift test
#clean test
# after_success:
#   - bash <(curl -s https://codecov.io/bash)